### ISSUE TITLE
Attempted to use a closed session

### ISSUE THREAD

**Issue by BCurbs** [anasselhoud/AI-MealBot#4]
When I run it it gives some errors including attempting to use closed session.

**Comment by anasselhoud** [comment]
Hello @1552937 ,

Can you please give more details about the error? I recommend copying the logs or sending a screenshot of the output.

**Comment by brewwmannsna** [comment]
Run id: WB4DF4
Log directory: /tmp/tflearn_logs/
---------------------------------
Training samples: 13
Validation samples: 0
--
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    model.load("model.tflearn")
  File "/usr/local/lib/python3.7/dist-packages/tflearn/models/dnn.py", line 302, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/usr/local/lib/python3.7/dist-packages/tflearn/helpers/trainer.py", line 500, in restore
    self.restorer.restore(self.session, model_file)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1290, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: /content/model.tflearn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 83, in <module>
    model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
  File "/usr/local/lib/python3.7/dist-packages/tflearn/models/dnn.py", line 206, in fit
    callbacks=callbacks)
  File "/usr/local/lib/python3.7/dist-packages/tflearn/helpers/trainer.py", line 344, in fit
    show_metric)
  File "/usr/local/lib/python3.7/dist-packages/tflearn/helpers/trainer.py", line 826, in _train
    tflearn.is_training(True, session=self.session)
  File "/usr/local/lib/python3.7/dist-packages/tflearn/config.py", line 95, in is_training
    tf.get_collection('is_training_ops')[0].eval(session=session)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 921, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 5512, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1114, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by brewwmannsna** [comment]
am not quite sure how any of this works but adding 
```
model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
model.save("model.tflearn")
```
after line 71 helped... the model trained....

**Comment by brewwmannsna** [comment]
update: chat is working too.... my fix worked :)

**Comment by BCurbs** [comment]
Thanks. Worked for me.

**Comment by anasselhoud** [comment]
@brewwmannsna  Feel free to make a pull request with these changes if possible. Thank you.
